# 
# Synthesis run script generated by Vivado
# 

set_param project.defaultXPMLibraries XPM_MEMORY
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/darkin/Workspace/Vivado_HLS/image_histogram/solution1/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path /home/darkin/Workspace/Vivado_HLS/image_histogram/solution1/impl/vhdl/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  /home/darkin/Workspace/Vivado_HLS/image_histogram/solution1/impl/vhdl/doHist_CTRL_BUS_s_axi.vhd
  /home/darkin/Workspace/Vivado_HLS/image_histogram/solution1/impl/vhdl/doHist.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/darkin/Workspace/Vivado_HLS/image_histogram/solution1/impl/vhdl/doHist.xdc
set_property used_in_implementation false [get_files /home/darkin/Workspace/Vivado_HLS/image_histogram/solution1/impl/vhdl/doHist.xdc]


synth_design -top doHist -part xc7z020clg484-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef doHist.dcp

catch { report_utilization -file doHist_utilization_synth.rpt -pb doHist_utilization_synth.pb }
