// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void doHist (
hls::stream<struct ap_axiu<8, 2, 5, 6 > >& inStream,
int histo[256]);
