# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/darkin/Workspace/Vivado_HLS/image_contrast_adj/solution1/impl/vhdl/doHistStretch.xdc

# IP: ip/doHistStretch_ap_fdiv_14_no_dsp_32/doHistStretch_ap_fdiv_14_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==doHistStretch_ap_fdiv_14_no_dsp_32 || ORIG_REF_NAME==doHistStretch_ap_fdiv_14_no_dsp_32}]

# IP: ip/doHistStretch_ap_fmul_2_max_dsp_32/doHistStretch_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==doHistStretch_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==doHistStretch_ap_fmul_2_max_dsp_32}]

# IP: ip/doHistStretch_ap_sitofp_4_no_dsp_32/doHistStretch_ap_sitofp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==doHistStretch_ap_sitofp_4_no_dsp_32 || ORIG_REF_NAME==doHistStretch_ap_sitofp_4_no_dsp_32}]
