// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// KERNEL_BUS
// 0x10 ~
// 0x1f : Memory 'kernel' (3 * 8b)
//        Word n : bit [ 7: 0] - kernel[4n]
//                 bit [15: 8] - kernel[4n+1]
//                 bit [23:16] - kernel[4n+2]
//                 bit [31:24] - kernel[4n+3]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDOIMGPROC_KERNEL_BUS_ADDR_KERNEL_BASE 0x10
#define XDOIMGPROC_KERNEL_BUS_ADDR_KERNEL_HIGH 0x1f
#define XDOIMGPROC_KERNEL_BUS_WIDTH_KERNEL     8
#define XDOIMGPROC_KERNEL_BUS_DEPTH_KERNEL     3

// CRTL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of operation
//        bit 31~0 - operation[31:0] (Read/Write)
// 0x14 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDOIMGPROC_CRTL_BUS_ADDR_AP_CTRL        0x00
#define XDOIMGPROC_CRTL_BUS_ADDR_GIE            0x04
#define XDOIMGPROC_CRTL_BUS_ADDR_IER            0x08
#define XDOIMGPROC_CRTL_BUS_ADDR_ISR            0x0c
#define XDOIMGPROC_CRTL_BUS_ADDR_OPERATION_DATA 0x10
#define XDOIMGPROC_CRTL_BUS_BITS_OPERATION_DATA 32

